### ISSUE TITLE
css linting

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#13]
https://github.com/stylelint/stylelint
https://github.com/postcss/postcss-bem-linter

**Comment by furzeface** [comment]
Currently preparing a [PR](https://github.com/PJL101/foley/compare/master...furzeface:feature/css-linting) for the first bit of this - adding `stylelint` and reporting into the build.

**Comment by phildotdev** [comment]
omfg I could kiss you!

**Comment by furzeface** [comment]
_Might_ give the `BEM linter` one a go too before tomorrow, had a look into it before the `stylelint` task but it was a bit convoluted in my opinion. May be worth splitting this issue out into 2?
