### ISSUE TITLE
consider dropping sass and use postcss only

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#135]
In the land before time, when Foley was at v0.0.1, sass wasn't actually included as postcss can do everything I required. Because I try and avoid nesting, my only real SASS feature was bem support, variables and sass-mq (or equivalent) and most importantly susy grid system.

The above things (with the exception of susy) are easily supported in postcss. The only consideration is what grid system to use (if any).

It would be nice to write 'pure' css and transpile it with postcss, like babel does now with es2015

**Comment by phildotdev** [comment]
This is blocked as I would like a Susy replacement. This could be CSS grids, especially if a polypill appears

**Comment by phildotdev** [comment]
Investigate: https://github.com/jo-asakura/postcss-neat

**Comment by furzeface** [comment]
:+1:

**Comment by furzeface** [comment]
Lol, I saw this issue and was just about to put a :+1: on it. Then realised I did that yesterday. I must be asleep.

**Comment by furzeface** [comment]
https://github.com/jonathantneal/precss/blob/master/README.md

**Comment by furzeface** [comment]
I'm going to do that ^
