### ISSUE TITLE
can critical css task be added to 'gulp' task & watch?

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#28]

**Comment by furzeface** [comment]
I would probably only do this on a build/deploy, unless you want to do perf tests on local regularly?

**Comment by phildotdev** [comment]
You are probably right on that but it would have been nice to see it as part of the dev workflow. Just incase it produces errors and alike. 

I'm still investigating how to get decent perf testing in.

**Comment by furzeface** [comment]
Yes true, I've found it a little flaky recently and it has actually caused small errors, so might be wise to keep it in as a dev task for now and monitor the results, then when confident just have it as a deploy task. :octocat:

**Comment by furzeface** [comment]
Maybe not do it on `watch` though, could affect build speed?

**Comment by phildotdev** [comment]
I did that in a previous test. I had it building on dev but it was simply appending the inline css over and over on each watch.

**Comment by phildotdev** [comment]
Can't make this work accurately
