### ISSUE TITLE
investigate replacing susy with lost grid

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#344]
If I'm going to do this, it needs to be ASAP before documentation starts.

https://github.com/peterramsing/lost

**Comment by gbbns** [comment]
+1 for this. I've only done a quick demo with `lost` but it looks mega.

**Comment by gbbns** [comment]
Closed?

**Comment by phildotdev** [comment]
I'm building a new workflow as this one is now 3 years old 😱 Feels like a good time for a fresh start.
