### ISSUE TITLE
add basic print styles

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#356]

**Comment by furzeface** [comment]
https://github.com/furzeface/danielfurze.co.uk/blob/master/source/styles/_trumps.print.scss might help


@see {@link http://www.noupe.com/design/css-perfect-print-stylesheet-98272.html}

**Comment by furzeface** [comment]
TBH I can PR with this in if you want?

**Comment by phildotdev** [comment]
Thanks for the resources! I'll take a look but I'm more than happy to do it myself once 0.6.0 is done
