### ISSUE TITLE
tota11y

### ISSUE THREAD

**Issue by phildotdev** [fephil/foley#9]
https://github.com/Khan/tota11y

dev task only

**Comment by furzeface** [comment]
:+1:  Tota11y is awesome :sunglasses:

**Comment by phildotdev** [comment]
This is blocked as it's not building with webpack

**Comment by phildotdev** [comment]
add to auditsite task

**Comment by phildotdev** [comment]
Idea for a new gulp task:
- Copy totally from node_modules to dist
- inject script tag to totally in html with gulp

**Comment by furzeface** [comment]
Could use wiredep for this perhaps? Then you could use it to inject other dependencies into your markup, also you could inject seperate bundles for different environments? :octocat:

**Comment by phildotdev** [comment]
I definitely could but the current plan is to have a `gulp audit` task which does a few things. The idea is to keep totally away from the dev process and have it as a separate thing.

**Comment by phildotdev** [comment]
This is on hold as I am leaning towards suggesting using an external site tool instead.

**Comment by phildotdev** [comment]
Let's put this back in as a quick informal a11y test.

Use: https://github.com/mikehazell/gulp-inject-string and copy js file on a special task
